Desktop javascript
MohamedRoshdy2021/mobile-first-project pull request #9
Opened 2023-05-18 18:56 UTC by MohamedRoshdy2021

in this Pr i have
- Removed the data from HTML into dynamic javascript objects 
- Added the layout for pop up window 
- Added the styling for the pop-up window

2023-05-18 19:33 UTC, AbayomiOlaoye requested changes
Hi @MohamedRoshdy2021 :wave: , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![invalid](https://user-images.githubusercontent.com/99715640/211858554-39090b6b-2f0f-45dd-b5e0-8fb805e56431.gif)

## Invalid Code Review Request

You have submitted a pull request with no contribution from your partner as the project requirement asked that you do. Kindly work on this with your partner and submit a new PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-19 15:40 UTC, Zuhaib042 reviewed
Hi @MohamedRoshdy2021 @solog0039 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, that is a pair-programming activity and while your partner has made a commit, but that commit relates only to his contact information. for pair-programming  activities, it is necessary that both partners commit actual code in the project and not just mere changings in the readme file. kindly consider getting actual code commit from your partner.
- [ ] Also there is merge conflict in your pull request, kindly consider solving this merge conflict before submitting again because Github doesn't check for linters if there is merge conflict in the pull request.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-19 17:35 UTC, franclobo requested changes
Hi @MohamedRoshdy2021 and @solog0039, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/58642949/612891e9-7134-409a-9717-6e2a4f4ec848)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Good UI ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please let your partner doing the required changes to warranty equal participation in the pair-programing project. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 17:35 UTC, franclobo commented on js.js
> +    image: './img2/Snapshoot Portfolio desk4.JPG',
- [ ] Kindly correct the path of the image for a better UI. 👇🏽 

![image](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/58642949/942708cf-e69a-4260-88c8-c3df0a720821)

2023-05-19 17:35 UTC, franclobo commented on style.css
> +}
- [ ] The modal window looks incomplete in the mobile version, I recommend using `overflow-y: scroll` for a better UI 👇🏽 

![image](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/58642949/032d0999-8854-408b-a88f-4dbbdb337c54)

2023-05-19 17:41 UTC, MohamedRoshdy2021 commented on js.js
> +    image: './img2/Snapshoot Portfolio desk4.JPG',
but the path is correct and the images works just fine for me !!!  @franclobo

2023-05-19 19:15 UTC, Munsa1 requested changes
Hi @MohamedRoshdy2021, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Passing Linters :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] Kindly consider fixing your design to match the given design. For example the modal header color and the close icon in your design does not match the figma design

Figma Template
![image](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/81932478/2d6ff27c-dbff-4015-8a86-b52454bed10a)

Your Design
![image](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/81932478/bfddc6a4-ce6d-45c2-a9ee-4ee284855b33)
## Also note the missing grey overlay in your design
<br/>

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 19:15 UTC, Munsa1 commented on style.css
> +}
- [ ] As requested by the previous reviewer, kindly fix the view of the modal popup in mobile view by adding an `overflow-y: scroll;` effect as it helps improve the user experience.

Your View with the CSS Property
![image](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/81932478/e931466e-6ad9-4968-a6bc-ca1229930e26)

Your view without the CSS Property
![image](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/81932478/dbb44bea-e3e7-46c6-8493-98714109fd6d)

### Note that the style to the right on the first screenshot has the `overflow-y: auto` which makes the view more visible as the user is able to scroll down the modal page

2023-05-19 20:52 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hello team @MohamedRoshdy2021, @solog0039, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 🤓
✅ Linters tests passing. 👍
✅ Incorporates feedback from previous code reviews. 💯
✅ Populating the popup dynamically. 🎯
✅ Popup functionality working fine. 🙌

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-19 20:52 UTC, taldr27 commented on style.css
> +}
- [ ] **[OPTIONAL]** Great job incorporating all the changes requested by the previous reviewer! I have one more suggestion **that is entirely optional** but **could enhance the overall appearance and align it closely with the [provided template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=0-1&t=dplvWZodUXxA9pZz-0)**. You might consider **adding a blurry background when the pop-up is open on both desktop and mobile devices**. This small addition can provide a more polished and visually appealing experience. 🤓

  ![image](https://github.com/MohamedRoshdy2021/mobile-first-project/assets/107952724/3be98c8f-c4e7-4a3e-8679-249a3efc4a78)

2023-07-17 11:02 UTC, merged